name: Build docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Read config.json
        id: read-config
        run: |
          CONFIG=$(cat config.json)
          echo "::set-output name=config::$CONFIG"
          echo "Raw config output: $CONFIG"
          echo "Length of config: ${#CONFIG}" # Added to get config length
          if [ -z "$CONFIG" ]; then # Check if config is empty
            echo "config.json is EMPTY!"
            exit 1 # Exit the workflow
          fi
          jq --version

      - name: Check if config.json is a valid json
        run: |
          CONFIG=$(cat config.json)
          echo "$CONFIG" | jq .

      - name: Build and Copy Documentation
        run: |
          CONFIG=$(echo '${{ steps.read-config.outputs.config }}' | jq -c .)
          echo "Config after jq -c: $CONFIG"

          # Parse the JSON config file
          REPOS=$(echo "$CONFIG" | jq -r '.[]')

          echo "Repos after jq -r '.[]': $REPOS"

          # Iterate through the repositories
          for REPO in $(echo "$REPOS"); do
            # Extract the values from the JSON object
            NAME=$(echo "$REPO" | jq -r '.name')
            REPOSITORY=$(echo "$REPO" | jq -r '.repository')
            DOCS_PATH=$(echo "$REPO" | jq -r '.docsPath')
            OUTPUT_PATH=$(echo "$REPO" | jq -r '.outputPath')

            echo "Building documentation for $NAME ($REPOSITORY)"

            # Checkout the repository
            git clone --depth 1 "https://github.com/$REPOSITORY" "$NAME"

            # Build the documentation
            cd "$NAME/$DOCS_PATH"
            npm install
            npm run build
            cd ../../..

            # Create the output directory
            mkdir -p "$OUTPUT_PATH"

            # Copy the built documentation to the output directory
            cp -r "$NAME/$DOCS_PATH/build/"* "$OUTPUT_PATH/"

            # Clean up the checked-out repository
            rm -rf "$NAME"
          done

      - name: Commit and Push to origin
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git push origin main
