name: Build docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Changed from 23 to 20 as Node 23 might not be supported

      - name: Check config.json exists or create default
        id: config-check
        run: |
          if [ ! -f "config.json" ]; then
            echo "Config file not found, creating empty array"
            echo "[]" > config.json
            echo "has_config=false" >> $GITHUB_ENV
          else
            echo "has_config=true" >> $GITHUB_ENV
          fi

      - name: Build and Copy Documentation
        if: env.has_config == 'true'
        run: |
          CONFIG=$(cat config.json)
          echo "Config content: $CONFIG"

          # Check if config is empty array
          if [ "$CONFIG" = "[]" ]; then
            echo "Config is empty, nothing to build"
            exit 0
          fi

          # Iterate through the repositories
          echo "$CONFIG" | jq -c '.[]' | while read -r REPO; do
            # Extract the values from the JSON object
            NAME=$(echo "$REPO" | jq -r '.name')
            REPOSITORY=$(echo "$REPO" | jq -r '.repository')
            DOCS_PATH=$(echo "$REPO" | jq -r '.docsPath')
            OUTPUT_PATH=$(echo "$REPO" | jq -r '.outputPath')

            echo "Building documentation for $NAME ($REPOSITORY)"

            # Checkout the repository
            git clone --depth 1 "https://github.com/$REPOSITORY" "$NAME"

            # Build the documentation
            cd "$NAME/$DOCS_PATH"
            npm install
            npm run build
            cd ../../..

            # Create the output directory
            mkdir -p "$OUTPUT_PATH"

            # Copy the built documentation to the output directory
            cp -r "$NAME/$DOCS_PATH/build/"* "$OUTPUT_PATH/"

            # Clean up the checked-out repository
            rm -rf "$NAME"
          done

      - name: Commit and Push to origin
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git push origin main
